### ISSUE TITLE
Specify Python compatibility requirements

### ISSUE THREAD

**Issue by thundergolfer** [dillon-giacoppo/rules_python_external#24]
### Description

Our code uses `f-strings` which are only available in >= Python 3.6. We should remove them or at least specify in the `README` that we don't support <= 3.5

**Comment by dillon-giacoppo** [comment]
Python 3.5 is not EOL until September 13 2020 (https://devguide.python.org/#status-of-python-branches). I think it makes sense to support the oldest supported release of Python. I think the correct approach is to remove the `f-strings`.

I think its worth stating in the README that supported versions are 3.5+

**Comment by thundergolfer** [comment]
Agreed.

**Comment by dillon-giacoppo** [comment]
Fixed in 0.1.2
