### ISSUE TITLE
|pip_install| should respect toolchain

### ISSUE THREAD

**Issue by dayfine** [dillon-giacoppo/rules_python_external#36]
I recently started to using [`toolchain`](https://github.com/bazelbuild/rules_python/blob/master/docs/python.md) as I try to get deterministic behavior when running my codebase on CI.

Then I found that the `pip_install` performed by this repo still uses the system's `/usr/bin/python3` even if I configured the toolchain to use the py binary in the virtualenv. I think this rule should get the interpreter from the toolchain.

Even if I try to work around this issue by specifying `python_interpreter` for `pip_install`, it only accepts an absolute path. In other words, if I pass the same relative path to virtualevenv that I passed to the `py_runtime` rule's `interpreter` tag, it will error with:

```
INFO: Call stack for the definition of repository 'py_deps' which is a pip_repository (rule definition at /root/.cache/bazel/_bazel_root/9fe7f4f07a7276c7a0aa3365ae93522e/external/rules_python_external/defs.bzl:46:18):
 - <builtin>
 - /root/.cache/bazel/_bazel_root/9fe7f4f07a7276c7a0aa3365ae93522e/external/rules_python_external/defs.bzl:59:5
 - /root/xlab/WORKSPACE:78:1
ERROR: An error occurred during the fetch of repository 'py_deps':
   rules_python_external failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(.venv/bin/python3.8, ...)": No such file or directory
)
ERROR: no such package '@py_deps//': rules_python_external failed:  (src/main/tools/process-wrapper-legacy.cc:58: "execvp(.venv/bin/python3.8, ...)": No such file or directory
)
```

My commit: https://github.com/dayfine/xlab/commit/1097784048b8ff06604c77c314382260990ddfc0

**Comment by dillon-giacoppo** [comment]
Hi @dayfine, unfortunately, the platform (or toolchain) API is not exposed to repository_rules such as rules_python_external. Therefore it is not possible to accept a Python toolchain as a parameter and consume it.

To mitigate this issue, the rules support specifying a Python executable as either an absolute path or they use the `PATH` variable to determine which Python to run with. To achieve this, you can activate your virtual environment, thereby configuring the `PATH`. Therefore, in your case, the python interpreter should just be `"python3"` which is the default (or the analogous `"python3.8"` which is equivalent to `"python3"` for your linked configuration).

If this still does not work, please confirm that `source .venv/bin/activate` has taken effect when the `bazel build` step runs, i.e that they don't execute in different environments. This should be easily verified by inspecting either the `PATH` or the `VIRTUAL_ENV` environment variables.

As a separate issue, I don't believe relative paths to a Python interpreter have ever worked. IIUC, the repository_rules execute in the `$(bazel info output_base)/external` directory and without any context of the repository you are trying to build. I may be wrong, but I don't think its possible to accept relative paths.

**Comment by dayfine** [comment]
Uh thanks for your help. I dig into it, and indeed the `$VIRTUAL_ENV` that got set in one commend got magically unset in the next. I think there is some CircleCI nonsense about what state get carried from one command to the next.

So `pip_install` was able to infer the right python3 to invoke within the virtualenv, and there is no issue. Closing :)

P.S: the `py_runtime` rule in `rules_python` has two attributes: `interpreter` accepts a relative path and `interpreter_path` accepts an absolute path.
