### ISSUE TITLE
Including PyPl libraries with executable binaries

### ISSUE THREAD

**Issue by JoshuaCrestone** [dillon-giacoppo/rules_python_external#45]
I am trying to include a the [Modin](https://github.com/modin-project/modin) project as a dependency. This project uses [Ray](https://github.com/ray-project/ray) which in turn uses Redis.

When executing the py_test rule that exercises this code, I get the following permissions error:

```
PermissionError: [Errno 13] Permission denied: '/private/var/tmp/_bazel_joshuaharrison/29b3465cefdffc832f5dd334d22b0ea7/execroot/Crestone/bazel-out/darwin-fastbuild/bin/strategies/example/test_strategy_test.runfiles/pip/pypi__ray/ray/core/src/ray/thirdparty/redis/src/redis-server'
```

This file path is a symlink to /private/var/tmp/_bazel_joshuaharrison/29b3465cefdffc832f5dd334d22b0ea7/external/pip/pypi__ray/ray/core/src/ray/thirdparty/redis/src/redis-server which has the following permissions:

```
-rw-r--r--  1 joshuaharrison  wheel  1343096 Jun  9 16:10 /private/var/tmp/_bazel_joshuaharrison/29b3465cefdffc832f5dd334d22b0ea7/external/pip/pypi__ray/ray/core/src/ray/thirdparty/redis/src/redis-server
```

If I manually chmod this file into being executable, I get a separate error about another non-executable file. If I keep fixing these errors in the same manner, the test will eventually run and pass.

I understand that this is not an issue specific to your project, but was hoping for some help in figuring out a possible solution. For example, I suppose I could make all files executable in [extract_wheel](https://github.com/dillon-giacoppo/rules_python_external/blob/master/extract_wheels/lib/bazel.py#L119)?

Thoughts?

**Comment by dillon-giacoppo** [comment]
So it looks like the `ray` wheel does correctly have permissions set:

```sh
$ unzip -Z ray-0.8.5-cp38-cp38-macosx_10_13_x86_64.whl | grep redis-server
-rwxr-xr-x  2.0 unx  1343096 b- defN 20-May-06 22:05 ray-0.8.5.data/purelib/ray/core/src/ray/thirdparty/redis/src/redis-server
```

It looks like there are known problems, [issue15795](https://bugs.python.org/issue15795) and [issue18262](https://bugs.python.org/issue18262), with [`ZipFile.extractall`](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extractall) which means it does not preserve permissions. 

I don't think we should just blindly make all files executable when extracting. There are some simple workarounds we can try [here](https://stackoverflow.com/questions/39296101/python-zipfile-removes-execute-permissions-from-binaries) and also a more comprehensive workaround that takes the OS architecture into account [here](https://stackoverflow.com/a/46837272).

We might be best to take notes from the Pip implementation https://github.com/pypa/pip/blob/cc48c07b64f338ac5e347d90f6cb4efc22ed0d0b/src/pip/_internal/utils/unpacking.py#L240 which looks to preserve permissions.

**Comment by JoshuaCrestone** [comment]
Thank you for the detailed analysis! This is great.

So are you open to a patch that applies chmod +x to files with any execute permissions?
