### ISSUE TITLE
Depending on wheels installed from URL (i.e. pip --find-links)

### ISSUE THREAD

**Issue by bsarden** [dillon-giacoppo/rules_python_external#51]
Hello,

I'm trying to depend on a version of the `torch-nightly` installs by specifying the URL of the wheel in the requirements.txt. Is this behavior supported?

From the torch docs (which recommends using `--find-links` option on pip), I'd like to have a requirements.txt with the following url.

equivalent pip install cmd:

```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

contents of the requirements.txt file:

```
https://download.pytorch.org/whl/nightly/cu102/torch-1.7.0.dev20200723-cp37-cp37m-linux_x86_64.whl
```

locally this would install with the following torch version.

```python
import torch
print(torch.__version) # 1.7.0.dev20200723
```

However, this seems to break on the `pip_install` rule.

Maybe there's a workaround?

**Comment by dillon-giacoppo** [comment]
The [full specification](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) of requirements.txt is supported, so the following behavior can be achieved with the following requirements.txt file:

```
--pre 
-f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
torchvision
torch
```

When I run this I get: `1.7.0.dev20200815`.

Note, that `pre` and `f` are global and cannot be specified per requirement.
