### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by alexeagle** [dillon-giacoppo/rules_python_external#59]
This has now been upstreamed to rules_python and released in 0.1.0.

I think to prevent confusion this repo should be archived with a message pointing to that release notes
https://github.com/bazelbuild/rules_python/releases/tag/0.1.0

Also maybe leave a note on the three outstanding PRs that they should be ported, and do something with the two open issues?

Thanks for this awesome work that is now canonical :)

**Comment by dillon-giacoppo** [comment]
🥳 Thanks @alexeagle for all your work getting this upstream. Will update the README and archive
